// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDROXZb8UFIXXaZx0kecpazKfpGJYxoAJU',
    appId: '1:151042498941:web:18f2a3ff43a07173efec14',
    messagingSenderId: '151042498941',
    projectId: 'crave-guest-registration-d2600',
    authDomain: 'crave-guest-registration-d2600.firebaseapp.com',
    storageBucket: 'crave-guest-registration-d2600.appspot.com',
    measurementId: 'G-5WS0FMRSYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ50kCV2WLGV6tKsMA6fqNua9n4QH3SYs',
    appId: '1:151042498941:android:99fd91b33c7fbe33efec14',
    messagingSenderId: '151042498941',
    projectId: 'crave-guest-registration-d2600',
    storageBucket: 'crave-guest-registration-d2600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu0NToUBR6AwQAGkYvdK-sAmQ_BEbKRew',
    appId: '1:151042498941:ios:2408a87ebba67332efec14',
    messagingSenderId: '151042498941',
    projectId: 'crave-guest-registration-d2600',
    storageBucket: 'crave-guest-registration-d2600.appspot.com',
    iosClientId: '151042498941-n5upgjcdh2pc9knri2cij1vro38k1tmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.craveGuestRegistartion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu0NToUBR6AwQAGkYvdK-sAmQ_BEbKRew',
    appId: '1:151042498941:ios:2408a87ebba67332efec14',
    messagingSenderId: '151042498941',
    projectId: 'crave-guest-registration-d2600',
    storageBucket: 'crave-guest-registration-d2600.appspot.com',
    iosClientId: '151042498941-n5upgjcdh2pc9knri2cij1vro38k1tmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.craveGuestRegistartion',
  );
}
